# original file name kube-node-drainer-ds.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "kube-asg-node-drainer.name" . }}
  labels: {{ include "kube-asg-node-drainer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "kube-asg-node-drainer.matchLabels" . | nindent 6 }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "kube-asg-node-drainer.labels" . | nindent 8 }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: {{ template "kube-asg-node-drainer.name" . }}
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
        - operator: Exists
          key: CriticalAddonsOnly
      containers:
        - name: kube-node-drainer
          image: {{.Values.image}}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ASG_LIFECYCLE_HOOK_NAME
              value: {{ template "kube-asg-node-drainer.name" . }}
          command:
            - /usr/local/bin/node-drainer
          volumeMounts:
            - mountPath: /etc/kube-node-drainer
              name: kube-node-drainer-status
              readOnly: true
      volumes:
        - name: kube-node-drainer-status
          projected:
            sources:
              - configMap:
                  name: kube-node-drainer-status
                  optional: true
