# original file name kube-node-drainer-asg-status-updater-de.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kube-asg-node-drainer.name" . }}-status-updater
  labels: {{ include "kube-asg-node-drainer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "kube-asg-node-drainer.matchLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels: {{ include "kube-asg-node-drainer.labels" . | nindent 8 }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        {{if ne .Values.iamRole "" -}}
        iam.amazonaws.com/role: {{ .Values.iamRole }}
    {{ end }}
    spec:
      serviceAccountName: {{ template "kube-asg-node-drainer.name" . }}
      priorityClassName: system-node-critical
      containers:
        - name: {{ template "kube-asg-node-drainer.name" . }}-status-updater
          image: {{.Values.image}}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - /usr/local/bin/asg-configmap-updater