apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "kube-asg-node-drainer.name" . }}
    release: {{ template "kube-asg-node-drainer.name" . }}
    heritage: "{{ .Release.Service }}"
  name: {{ template "kube-asg-node-drainer.name" . }}
  namespace: {{ .Release.Namespace}}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resourceNames:
      - kube-node-drainer-status
    resources:
      - configmaps
    verbs:
      - get
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - "apps"
    resources:
      - daemonsets
      - replicasets
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups:
      - "apps"
    resources:
      - daemonsets
    verbs:
      - get
