apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app: {{ template "name" . }}
        release: {{ template "name" . }}
        heritage: "{{ .Release.Service }}"
    name: {{ template "name" . }}
    namespace: {{ .Release.Namespace}}
