---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS - Drainer ASG Hook'

Parameters:

  AsgName:
    Description: ASG Name
    Type: String

  HookName:
    Description: ASG Lifecycle hook name
    Type: String
    Default: kube-asg-node-drainer

  NodeTerminationTimeout:
    Description: ASG Lifecycle hook heartbeat
    Type: Number
    Default: 900
    MinValue: 30
    MaxValue: 7200

Resources:

  # to allow proper draining for the nodes evicted during rebalancing
  NodeGroupLifeCycleHook:
    Type: AWS::AutoScaling::LifecycleHook
    Properties:
      LifecycleHookName: !Ref HookName
      AutoScalingGroupName: !Ref AsgName
      LifecycleTransition: "autoscaling:EC2_INSTANCE_TERMINATING"
      DefaultResult: CONTINUE
      HeartbeatTimeout: !Ref NodeTerminationTimeout
